#! /bin/sh

if test $# -lt 1
then
	echo Usage: $0 N
	echo Run a shell on node N.
	exit 1
fi

n=$1
shift

if test $# -gt 0
then
	exec ip netns exec node$n bash -c "$*"
else
	exec ip netns exec node$n bash
fi
