#! /bin/sh

iptables -t mangle -D FORWARD -d 10.0.0.1 -p tcp -j TCPR --addr 10.0.2.1
iptables -t mangle -D FORWARD -d 10.0.0.1 -p udp -j TCPR --addr 10.0.2.1
iptables -t mangle -D FORWARD -s 10.0.0.1 -p tcp -j TCPR

rmmod tcpr
